# Generated by Django 4.0 on 2025-01-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='本文')),
                ('posted_at', models.DateField(auto_now_add=True, verbose_name='投稿日時')),
                ('category', models.CharField(choices=[('science', '科学'), ('IT', 'IT'), ('sports', 'スポーツ'), ('entertainment', 'エンタメ'), ('economy', '経済'), ('international', '国際'), ('domestic', '国内')], max_length=50, verbose_name='カテゴリ')),
            ],
        ),
    ]
